--COMENTARIO MULTIPLAS LINHAS -> /*

--DDL - CRIAR -> CRATE (SCHEMA, TABELA)
CREATE SCHEMA CLINICA;

--CREATE TABLE<SCHEMA>.<NOME_DA_TABELA>
CREATE TABLE CLINICA.MEDICO(
	--INFORMAR COLUNAS
	--NOME_DA_COLUNA TIPO_DE_DADO
	--GENERATED ALWAYS AS IDENTITY - A CHAVE É CRIADA AUTOMATICAMENTE
	ID_MEDICO INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOME TEXT NOT NULL,
	CRM TEXT NOT NULL,
	ESPECIALIDADE TEXT NOT NULL
);
CREATE TABLE CLINICA.PACIENTE(
	ID_PACIENTE INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOME TEXT NOT NULL,
	IDADE INT NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
);
CREATE TABLE CLINICA.CLINICA(
	ID_CLINICA INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOME TEXT NOT NULL,
	DESCRICAO TEXT NOT NULL,
	ENDERECO TEXT
);

CREATE TABLE CLINICA.CONSULTA(
	ID_CONSULTA INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	DATA TIMESTAMPTZ NOT NULL,
	VALOR NUMERIC (10,4),
	ID_MEDICO  INT NOT NULL,
	FOREIGN KEY (ID_MEDICO) REFERENCES CLINICA.MEDICO(ID_MEDICO),
	ID_CLINICA INT NOT NULL REFERENCES CLINICA.CLINICA(ID_CLINICA),
	ID_PACIENTE INT NOT NULL REFERENCES CLINICA.PACIENTE(ID_PACIENTE)
);




--ALTER - ALTERAR TABELA (ADICIONAR COLUNA)
ALTER TABLE CLINICA.PACIENTE ADD COLUMN CPF VARCHAR(14) UNIQUE;

--APAGAR COLUNA
ALTER TABLE CLINICA.PACIENTE DROP COLUMN CPF;

--RENOMEAR COLUNA
ALTER TABLE CLINICA.NOVOPACIENTE RENAME TO PACIENTE;

--TRUNCATE - LIMPA A TABELA
TRUNCATE TABLE CLINICA.CONSULTA;

--RESTART IDENTITY - REINICIA A SEQUENCIA
RESTART IDENTITY;

--APAGAR TABELAS - DROP
DROP TABLE IF EXISTS CLINICA.CONSULTA;
DROP TABLE  CLINICA.CONSULTA;
DROP TABLE CLINICA.CLINICA;
DROP TABLE CLINICA.PACIENTE;
DROP TABLE CLINICA.MEDICO;
