CREATE SCHEMA techmarket;

--DROP SCHEMA "Techmarket";

CREATE TABLE TECHMARKET.CLIENTE(
	CLIENTE_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOME_COMPLETO TEXT NOT NULL,
	EMAIL VARCHAR(50),
	SENHA TEXT NOT NULL,
	TELEFONE INT NOT NULL
);
CREATE TABLE TECHMARKET.PEDIDO(
	PEDIDO_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	CLIENTE_ID INT,
	FOREIGN KEY (CLIENTE_ID) REFERENCES TECHMARKET.CLIENTE(CLIENTE_ID),
	DATA_PEDIDO TIMESTAMPTZ,
	VALOR_TOTAL NUMERIC(18,4),
	STATUS TEXT NOT NULL
);
CREATE TABLE TECHMARKET.PRODUTO(
	PRODUTO_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOME_PRODUTO TEXT NOT NULL,
	DESCRICAO TEXT NOT NULL,
	PRECO INT NOT NULL,
	ESTOQUE_DISPONIVEL INT NOT NULL,
	IMAGEM_URL TEXT NOT NULL
);
CREATE TABLE TECHMARKET.ITEM_DO_PEDIDO(
	ITEM_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	PEDIDO_ID INT,
	FOREIGN KEY (PEDIDO_ID) REFERENCES TECHMARKET.PEDIDO(PEDIDO_ID),
	PRODUTO_ID INT,
	FOREIGN KEY (PRODUTO_ID) REFERENCES TECHMARKET.PRODUTO(PRODUTO_ID),
	QUANTIDADE INT NOT NULL
);
CREATE TABLE TECHMARKET.PAGAMENTO(
	PAGAMENTO_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	PEDIDO_ID INT,
	FOREIGN KEY (PEDIDO_ID) REFERENCES TECHMARKET.PEDIDO(PEDIDO_ID),
	FORMA_PAGAMENTO TEXT NOT NULL,
	STATUS TEXT NOT NULL,
	DATA_PAGAMENTO TIMESTAMPTZ
);
